FROM golang:1.8

ADD . /go/src/github.com/yezzey-gp/aws-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/github.com/yezzey-gp/aws-sdk-go
CMD ["make", "get-deps", "unit-old-go-race-cover"]
