// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package sagemakermetrics

import (
	"github.com/yezzey-gp/aws-sdk-go/private/protocol"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{}
